apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argocd-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/janus-qe/RHDH-ArgoCD-plugin-test
    targetRevision: HEAD
    path: resources
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
